
sub: main.o
	g++ -o sub -lsyllable -lstdc++ main.o
                                                                                                                                                                                                        
main.o: main.cpp
	g++ -Wall -c main.cpp
                                                                                                                                                                                                        
clean:
	rm -f main.o
	rm -f sub
